# Generated by Django 3.2.9 on 2021-11-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judicial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_number',
            field=models.CharField(max_length=100),
        ),
    ]
